spring:
  application:
    name: graphql-todo-app
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    multipart:
      enabled: true
      location: /tmp
  graphql:
    tools:
      schemaLocationPattern: "**/*.graphqls"
      # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
      # specification and expectations of most clients, so use this option with caution
      introspectionEnabled: true
server:
  port: 8080